trigger:
  branches:
    include:
      - main

pool:
 name: MyLocalAgent

variables:
  PORT: '5000'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build the project'

- script: |
    echo "Running SonarQube analysis (mock)"
  displayName: 'SonarQube Code Analysis'

- script: |
    npm test
  displayName: 'Run Unit Tests with Coverage'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'dist'
    artifactName: 'drop'
  displayName: 'Publish Artifact'

- script: echo "Delivering build artifact..."
  displayName: 'Deliver Stage'

- script: echo "Deploying to Dev on port $(PORT)"
  displayName: 'Deploy to Dev Environment'

- script: echo "Mock QAT Deployment"
  displayName: 'Deploy to QAT'

- script: echo "Mock Staging Deployment"
  displayName: 'Deploy to Staging'

- script: echo "Mock Production Deployment"
  displayName: 'Deploy to Production'
- script: npm install
  displayName: 'Install dependencies'



