trigger:
  branches:
    include:
      - main

pool:
  name: MyLocalAgent

variables:
  PORT: '5000'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQube-Service' 
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'DevOpsCIProject'
    cliProjectName: 'DevOps CI Project'
    cliSources: '.'
  displayName: 'Prepare SonarQube Analysis'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build the project'

- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube Analysis'

- script: |
    npm test
  displayName: 'Run Unit Tests with Coverage'

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarQube Report'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'dist'
    artifactName: 'drop'
  displayName: 'Publish Artifact'

- script: echo "Delivering build artifact..."
  displayName: 'Deliver Stage'

- script: echo "Deploying to Dev on port $(PORT)"
  displayName: 'Deploy to Dev Environment'

- script: echo "Mock QAT Deployment"
  displayName: 'Deploy to QAT'

- script: echo "Mock Staging Deployment"
  displayName: 'Deploy to Staging'

- script: echo "Mock Production Deployment"
  displayName: 'Deploy to Production'

- script: npm install
  displayName: 'Install dependencies'

- script: npm test
  displayName: 'Run unit tests with coverage'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
