trigger:
  branches:
    include:
      - main

pool:
  name: MyLocalAgent

variables:
  PORT: '5000'

steps:
# ✅ Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# ✅ Install dependencies
- script: |
    npm install
  displayName: 'Install dependencies'

# ✅ Build the project (if you have a build script)
- script: |
    npm run build
  displayName: 'Build the project'

# ✅ Run Unit Tests with Coverage
- script: |
    npm test
  displayName: 'Run unit tests with coverage'

# ✅ Publish Code Coverage Results
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'

# ✅ Copy build output to staging folder
- task: CopyFiles@2
  displayName: 'Copy files to staging'
  inputs:
    contents: '**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

# ✅ Publish Artifact (you'll see "drop" under Artifacts)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

# ✅ Simulated Delivery and Deployments
- script: echo "Delivering build artifact..."
  displayName: 'Deliver Stage'

- script: echo "Deploying to Dev on port $(PORT)"
  displayName: 'Deploy to Dev Environment'

- script: echo "Mock QAT Deployment"
  displayName: 'Deploy to QAT'

- script: echo "Mock Staging Deployment"
  displayName: 'Deploy to Staging'

- script: echo "Mock Production Deployment"
  displayName: 'Deploy to Production'
