trigger:
  branches:
    include:
      - main

pool:
  name: MyLocalAgent

variables:
  PORT: '5000'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build the project'

- script: |
    npm test
  displayName: 'Run Unit Tests with Coverage'

# ✅ Copy to Artifact Staging Directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/src'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'
  displayName: 'Copy files to staging folder'

# ✅ Publish Artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/drop'
    artifactName: 'drop'
  displayName: 'Publish Artifact'

# ---- Delivery/Deployment Stages (Mocked) ----
- script: echo "Delivering build artifact..."
  displayName: 'Deliver Stage'

- script: echo "Deploying to Dev on port $(PORT)"
  displayName: 'Deploy to Dev Environment'

- script: echo "Mock QAT Deployment"
  displayName: 'Deploy to QAT'

- script: echo "Mock Staging Deployment"
  displayName: 'Deploy to Staging'

- script: echo "Mock Production Deployment"
  displayName: 'Deploy to Production'

# ---- Optional: Rerun tests for coverage upload ----
- script: npm install
  displayName: 'Install dependencies again'

- script: npm test
  displayName: 'Run unit tests again'

# ✅ Code Coverage Reporting
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
  displayName: 'Publish Code Coverage'
